In [1]:
import numpy as np

# Data Types & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1


array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 =np.array([[1,2.0,3.3],
              [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4, 5,6],
               [10,11,12]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# create a dataframe from a numpy array

In [14]:
import pandas as pd
df1 = pd.DataFrame(a1)
df = pd.DataFrame(a2)


## Must pass 2-d input. shape=(2, 3, 3)
## df3 = pd.DataFrame(a3)

In [15]:
df1

0
0  1
1  2
2  3

In [16]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating arrays

In [17]:
sample_array =np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones(shape = (2,3), dtype=float)
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array =np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[8, 7, 8, 2, 6],
       [5, 5, 5, 7, 3],
       [9, 1, 2, 2, 5]], dtype=int32)

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 =np.random.random(size =(5,3))
random_array_2

array([[0.72264098, 0.32553755, 0.35613926],
       [0.31709174, 0.25155719, 0.19404845],
       [0.17755331, 0.72567924, 0.20901078],
       [0.67470667, 0.52902463, 0.45471414],
       [0.91184307, 0.21376721, 0.56440777]])

In [27]:
random_array_2.shape

(5, 3)

In [28]:
random_array_3 = np.random.randn(5,3)
random_array_3

array([[ 0.10418723,  1.80785996, -1.3164396 ],
       [-1.06490704, -0.42697636, -0.66140195],
       [-0.16928456,  0.48236187, -1.56561161],
       [ 0.01959279, -0.45769024, -0.81145125],
       [ 1.24538245,  0.57871844,  1.72159088]])

# Pseudo-random numbers (How to generate non-random random numbers)

In [29]:
np.random.seed(seed=42)
random_array_4 = np.random.random((5,3))
random_array_4

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

## Viewing arrays and matrices

In [30]:
random_array_5 =  np.random.randint(0,10,size=(5,3))
random_array_5

array([[4, 0, 9],
       [5, 8, 0],
       [9, 2, 6],
       [3, 8, 2],
       [4, 2, 6]], dtype=int32)

In [31]:
np.unique(random_array_5)

array([0, 2, 3, 4, 5, 6, 8, 9], dtype=int32)

In [32]:
a1

array([1, 2, 3])

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a1[0], a2[0], a3[0]

(np.int64(1),
 array([1. , 2. , 3.3]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12]]))

In [36]:
a1[1], a2[1], a3[1]

(np.int64(2),
 array([4. , 5. , 6.5]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [37]:
a3[:2, :2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [38]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[4, 8, 6, 1, 3],
         [8, 1, 9, 8, 9],
         [4, 1, 3, 6, 7],
         [2, 0, 3, 1, 7]],

        [[3, 1, 5, 5, 9],
         [3, 5, 1, 9, 1],
         [9, 3, 7, 6, 8],
         [7, 4, 1, 4, 7]],

        [[9, 8, 8, 0, 8],
         [6, 8, 7, 0, 7],
         [7, 2, 0, 7, 2],
         [2, 0, 4, 9, 6]]],


       [[[9, 8, 6, 8, 7],
         [1, 0, 6, 6, 7],
         [4, 2, 7, 5, 2],
         [0, 2, 4, 2, 0]],

        [[4, 9, 6, 6, 8],
         [9, 9, 2, 6, 0],
         [3, 3, 4, 6, 6],
         [3, 6, 2, 5, 1]],

        [[9, 8, 4, 5, 3],
         [9, 6, 8, 6, 0],
         [0, 8, 8, 3, 8],
         [2, 6, 5, 7, 8]]]], dtype=int32)

In [39]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [40]:
# Get the first 4 numbers of the inner most arrays: from shape outer most number is the inner most number
a4[:,:,:,:2]

array([[[[4, 8],
         [8, 1],
         [4, 1],
         [2, 0]],

        [[3, 1],
         [3, 5],
         [9, 3],
         [7, 4]],

        [[9, 8],
         [6, 8],
         [7, 2],
         [2, 0]]],


       [[[9, 8],
         [1, 0],
         [4, 2],
         [0, 2]],

        [[4, 9],
         [9, 9],
         [3, 3],
         [3, 6]],

        [[9, 8],
         [9, 6],
         [0, 8],
         [2, 6]]]], dtype=int32)

## 4. Manipulating and Comparing Arrays

### Arithmatic

In [41]:
a1

array([1, 2, 3])

In [42]:
ones =np.ones(3)
ones

array([1., 1., 1.])

In [43]:
a1+ones

array([2., 3., 4.])

In [44]:
a1- ones

array([0., 1., 2.])

In [45]:
a1*ones

array([1., 2., 3.])

In [46]:
a1

array([1, 2, 3])

In [47]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [48]:
a1.shape, a2.shape

((3,), (2, 3))

In [49]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

### How can you reshape a2 to be compatible with a3? Search the broadcast
#### How to reshape numpy array
###  a2*a3

In [52]:
a1 / ones

array([1., 2., 3.])

In [53]:
# Floor division removes the decimals (round down)
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [54]:
a2*2

array([[ 2. ,  4. ,  6.6],
       [ 8. , 10. , 13. ]])

In [55]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [56]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [57]:
a1+ones

array([2., 3., 4.])

In [58]:
np.add(a1,ones)

array([2., 3., 4.])

In [59]:
a1%2

array([1, 0, 1])

In [60]:
a2%2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [61]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [62]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregration

Aggregation = performing the same operation on a number of things

In [63]:
listy_list  = [1,2,3]
type(listy_list)

list

In [64]:
sum(listy_list)

6

In [65]:
a1

array([1, 2, 3])

In [66]:
np.sum(a1)

np.int64(6)

# Use Python's method (sum()) on Python datatypes and use
# NumPy's methods (np.sum()) on NumPy arrays

In [67]:
# creative a massive numpy array
massive_array = np.random.random(10000)
massive_array.size

10000

In [68]:
massive_array

array([0.48482997, 0.69243603, 0.26941233, ..., 0.01556255, 0.64596426,
       0.43480153], shape=(10000,))

In [69]:
%timeit sum(massive_array) # python's sum()
%timeit np.sum(massive_array) # numpy sum()

396 μs ± 5.33 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
4.49 μs ± 19.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [70]:
np.mean(a2)

np.float64(3.6333333333333333)

In [71]:
np.min(a2)

np.float64(1.0)

In [72]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

np.float64(1.8226964152656422)

In [73]:
# Variance = measuer of the average degree to which each number is different to the mean
# Higher varinace = wider range of numbers
# Lower variance = lowder range of numbers
np.var(a2)

np.float64(3.3222222222222224)

In [74]:
# stadard deviation  =  squareroot of variance
np.sqrt(np.var(a2))

np.float64(1.8226964152656422)

In [75]:
# Demo of Std and var
high_var_array = np.array([1,100,200,300,400,5000])
low_var_array = np.array([2,4,6,8,10])

In [76]:
np.std(high_var_array),np.std(low_var_array), np.var(high_var_array), np.var(low_var_array)

(np.float64(1793.4139154757952),
 np.float64(2.8284271247461903),
 np.float64(3216333.4722222225),
 np.float64(8.0))